name: Daily Message

on:
  schedule:
    - cron: "0 4,16 * * *"

jobs:
  Post-Message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Extra Config
        run: echo $CONFIG_JSON | config.json
        env:
          CONFIG_JSON: ${{ env.CONFIG_JSON }}

      - name: Post Message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DEBUG_CHANNEL: ${{ env.DEBUG_CHANNEL }}
        run: node scripts/generateMessage.mjs
